seed: 42
device: cuda
multi_gpu: data_parallel
device_ids: [0, 1]

dataset:
  name: USPS
  root: dataset
  val_ratio: 0.2

model:
  type: resnet18
  embedding_dim: 16

training:
  batch_size: 256
  num_workers: 0
  lr: 0.001
  weight_decay: 0.0001
  epochs: 1
  patience: 1

ood:
  k: 3
  cov_reg: 0.001
