extends: ../_cmpt_affine_common.yaml

device: cuda:0
experiment:
  learner: iCaRL-common-affine
  expected_checkpoint_method: icarl
  checkpoints: outputs/cmpt/common_recipe/training/icarl_common_c100_b50_inc5_r32/seed_1/checkpoints
  output: outputs/cmpt/common_recipe/evaluation/icarl_affine_ridge1e-2/seed_1/cmpt_affine_matched_nme.json
