extends: evaluate_casper_il_affine.yaml

device: cuda:0
experiment:
  learner: CaSpeR-IL-herding-extrapolation
  output: outputs/cmpt/herding_extrapolation/cifar100/casper_il/seed_1/results.json

cmpt:
  herding_extrapolation:
    enabled: true
    full_prefix: 20
    reference_prefix: 10
