extends: evaluate_podnet_affine.yaml

device: cuda:0
experiment:
  learner: PODNet-full-training-mean-oracle
  output: outputs/cmpt/full_mean_oracle/cifar100/podnet/seed_1/results.json

cmpt:
  oracle_diagnostics:
    full_mean: true
