extends: evaluate_podnet_moment_transport.yaml

device: cuda:0
experiment:
  learner: PODNet-low-rank-moment-transport-rank8
  output: outputs/cmpt/moment_transport_rank8/cifar100/podnet/seed_1/results.json

cmpt:
  moment_transport:
    rank: 8
