extends: evaluate_podnet_affine.yaml

experiment:
  learner: PODNet-CMPT-component-ablation
  output: outputs/cmpt/component_ablation/cifar100/podnet/seed_1/results.json

cmpt:
  component_ablation:
    enabled: true
