extends: evaluate_icarl_affine.yaml

device: cuda:0
experiment:
  learner: iCaRL-full-training-mean-oracle
  output: outputs/cmpt/full_mean_oracle/cifar100/icarl/seed_1/results.json

cmpt:
  oracle_diagnostics:
    full_mean: true
