extends: _icarl_hierarchical_edge_correlation_common.yaml

method:
  edge_topology:
    representatives_per_class: 2
    lambda_edge: 15.0

output:
  run_name: icarl_edgecorr_r2_l15_c100_b50_inc5_r32
