from .afc import afc_nca_loss, afc_pod_loss, scheduled_afc_factor
from .branch_masked_kd import (
    BranchMaskedKDReference,
    BranchMaskedKDResult,
    branch_masked_pycil_icarl_kd_loss,
)
from .boundary_graph_surgery import (
    BOUNDARY,
    INSIDE,
    OUTSIDE,
    BoundaryGraphSurgeryLoss,
    BoundaryGraphSurgeryReference,
    bgs_insertion_loss,
    canonical_regions,
    endpoint_regions,
    negative_candidate_positions,
    pair_mask_summary,
    pair_types_and_weights,
    random_pair_seed,
    row_permuted_random_weights,
    tensor_sha256,
)
from .casper import casper_spectral_loss, neural_knn_weights
from .create import (
    ClassAutoencoder,
    ClasswiseAutoencoderClassifier,
    create_classification_loss,
    create_contrastive_loss,
    create_kd_loss,
    reconstruction_confidence_weights,
)
from .cscct import (
    controlled_transfer_loss,
    cosine_similarity_matrix,
    cross_space_clustering_loss,
)
from .fgp import (
    RectifiedCosineLinear,
    fgp_graph_preservation_loss,
    pairwise_squared_euclidean,
    scheduled_fgp_weight,
)
from .finetune import pycil_finetune_loss
from .global_hap import (
    ANCHOR_FRAME_MODES,
    ANCHOR_RELATION_OBJECTIVES,
    ANCHOR_WEIGHT_NORMALIZATIONS,
    AnchorGeometryLoss,
    hierarchical_triplet_rank_loss,
    inverse_angular_dispersion_reliability,
    weighted_anchor_correlation_loss,
)
from .hierarchical_edge_correlation import (
    EDGE_WEIGHTING_MODES,
    HierarchicalEdgeCorrelationLoss,
    HierarchicalEdgeReference,
    STRATIFIED_EDGE_GROUP_NAMES,
    StratifiedEdgeCorrelationResult,
    StratifiedHierarchicalEdgeCorrelationLoss,
    StratifiedHierarchicalEdgeReference,
    conflict_union_membership,
    conflict_subtree_inside_edge_weights,
    global_edge_weights,
    incident_edge_weights,
    pairwise_cosine_edge_vector,
    stratified_edge_group_ids,
    weighted_global_edge_correlation_loss,
)
from .icarl import (
    icarl_bce_loss,
    icarl_distillation_targets,
    parameter_l2_regularization,
    pycil_icarl_kd_loss,
)
from .logit_kd import old_logit_kl_loss
from .geodesic_distillation import (
    geodesic_distillation_loss,
    geodesic_flow_kernel,
    principal_subspace,
)
from .feature_cosine_distillation import (
    HierarchyRoutedFeatureWeights,
    cosine_feature_distillation_loss,
    cosine_imprinted_weights,
    hierarchy_routed_feature_sample_weights,
    normalized_cosine_classifier_logits,
)
from .podnet import (
    pod_flat_loss,
    pod_spatial_loss,
    podnet_nca_loss,
)
from .prototype_ce import prototype_cross_entropy, prototype_logits
from .projected_insertion import (
    ProjectedGradientResult,
    project_insertion_gradient,
)
from .replay_ce import (
    method_uses_afc,
    method_uses_dual_rebalancing,
    method_uses_geometry,
    method_uses_logit_kd,
    method_uses_topkd,
    method_uses_takp,
    replay_cross_entropy,
)
from .sacil_v0 import (
    ConflictWeights,
    compute_conflict_weights,
    global_preservation_weights,
)
from .selective_kd import (
    SelectiveKDResult,
    analytic_embedding_gradient_alignment,
    selective_pycil_icarl_kd_loss,
)
from .topology_kd import (
    RipsNet,
    TopologyDistillationLoss,
    load_frozen_ripsnet,
)
from .unified_contracts import (
    SUPPORTED_UNIFIED_METHODS,
    UnifiedMethodContract,
    unified_method_contract,
    validate_annotation1_config,
    validate_annotation1_protocol,
)
from .takp import takp_mixed_classification_loss

__all__ = [
    "AnchorGeometryLoss",
    "ANCHOR_FRAME_MODES",
    "ANCHOR_RELATION_OBJECTIVES",
    "ANCHOR_WEIGHT_NORMALIZATIONS",
    "BranchMaskedKDReference",
    "BranchMaskedKDResult",
    "BoundaryGraphSurgeryLoss",
    "BoundaryGraphSurgeryReference",
    "BOUNDARY",
    "INSIDE",
    "OUTSIDE",
    "EDGE_WEIGHTING_MODES",
    "HierarchicalEdgeCorrelationLoss",
    "HierarchicalEdgeReference",
    "STRATIFIED_EDGE_GROUP_NAMES",
    "StratifiedEdgeCorrelationResult",
    "StratifiedHierarchicalEdgeCorrelationLoss",
    "StratifiedHierarchicalEdgeReference",
    "ClassAutoencoder",
    "ClasswiseAutoencoderClassifier",
    "ConflictWeights",
    "HierarchyRoutedFeatureWeights",
    "cosine_feature_distillation_loss",
    "cosine_imprinted_weights",
    "hierarchy_routed_feature_sample_weights",
    "normalized_cosine_classifier_logits",
    "RectifiedCosineLinear",
    "SelectiveKDResult",
    "ProjectedGradientResult",
    "RipsNet",
    "TopologyDistillationLoss",
    "afc_nca_loss",
    "afc_pod_loss",
    "analytic_embedding_gradient_alignment",
    "branch_masked_pycil_icarl_kd_loss",
    "bgs_insertion_loss",
    "canonical_regions",
    "casper_spectral_loss",
    "compute_conflict_weights",
    "conflict_union_membership",
    "conflict_subtree_inside_edge_weights",
    "controlled_transfer_loss",
    "cosine_similarity_matrix",
    "create_classification_loss",
    "create_contrastive_loss",
    "create_kd_loss",
    "cross_space_clustering_loss",
    "fgp_graph_preservation_loss",
    "endpoint_regions",
    "global_preservation_weights",
    "geodesic_distillation_loss",
    "geodesic_flow_kernel",
    "hierarchical_triplet_rank_loss",
    "icarl_bce_loss",
    "icarl_distillation_targets",
    "pycil_finetune_loss",
    "pycil_icarl_kd_loss",
    "parameter_l2_regularization",
    "inverse_angular_dispersion_reliability",
    "load_frozen_ripsnet",
    "method_uses_afc",
    "method_uses_dual_rebalancing",
    "method_uses_geometry",
    "method_uses_logit_kd",
    "method_uses_topkd",
    "method_uses_takp",
    "replay_cross_entropy",
    "pair_types_and_weights",
    "random_pair_seed",
    "row_permuted_random_weights",
    "old_logit_kl_loss",
    "neural_knn_weights",
    "pairwise_squared_euclidean",
    "pod_flat_loss",
    "pod_spatial_loss",
    "podnet_nca_loss",
    "prototype_cross_entropy",
    "prototype_logits",
    "principal_subspace",
    "project_insertion_gradient",
    "reconstruction_confidence_weights",
    "scheduled_afc_factor",
    "scheduled_fgp_weight",
    "selective_pycil_icarl_kd_loss",
    "takp_mixed_classification_loss",
    "weighted_anchor_correlation_loss",
    "global_edge_weights",
    "incident_edge_weights",
    "pairwise_cosine_edge_vector",
    "stratified_edge_group_ids",
    "weighted_global_edge_correlation_loss",
    "SUPPORTED_UNIFIED_METHODS",
    "UnifiedMethodContract",
    "unified_method_contract",
    "validate_annotation1_config",
    "validate_annotation1_protocol",
]
