experiment:
  name: fgvc-aircraft-clip-features
  output_root: outputs

runtime:
  device: cuda

dataset:
  name: fgvc-aircraft
  datadir: D:/HY_Data/HierOOD/fgvc-aircraft
  hierarchy: hierarchies/fgvc-aircraft.json
  id_split: data/fgvc-aircraft-id-labels.csv

clip:
  model: openai/clip-vit-base-patch32
  local_files_only: true

dataloader:
  batch_size: 128
  num_workers: 4

feature_extraction:
  skip_train: true
