experiment:
  name: fgvc-aircraft-prompt-inspection

dataset:
  name: fgvc-aircraft
  hierarchy: hierarchies/fgvc-aircraft.json
  id_split: data/fgvc-aircraft-id-labels.csv

prompt_inspection:
  nodes:
    - m-Boeing
    - f-Boeing_737
    - v-737-300
  parents:
    - root
    - m-Boeing
    - f-Boeing_737
