extends: _common_b50_inc5.yaml
method:
  name: icarl
  kd_temperature: 2.0
training:
  batch_size: 128
  base:
    epochs: 200
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    scheduler: multistep
    milestones: [60, 120, 170]
    lr_decay: 0.1
  incremental:
    epochs: 170
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0002
    scheduler: multistep
    milestones: [80, 120]
    lr_decay: 0.1
output:
  run_name: icarl_pycil_semantics_nme_c100_b50_inc5_r32
