extends: evaluate_icarl_affine.yaml

experiment:
  learner: iCaRL-ImageNet100-CMPT-component-ablation
  output: outputs/cmpt/component_ablation/imagenet100/icarl/seed_1/results.json

cmpt:
  component_ablation:
    enabled: true
