extends: _cmpt_affine.yaml

device: cuda:1
experiment:
  learner: PODNet-ImageNet100
  expected_checkpoint_method: podnet
  checkpoints: outputs/cmpt/imagenet100_b50_inc5/training/podnet_imagenet100_b50_inc5_r18/seed_1/checkpoints
  output: outputs/cmpt/imagenet100_b50_inc5/evaluation/podnet/seed_1/cmpt_affine_ridge.json
