extends: evaluate_casper_il_affine.yaml

experiment:
  learner: CaSpeR-IL-ImageNet100-CMPT-component-ablation
  output: outputs/cmpt/component_ablation/imagenet100/casper_il/seed_1/results.json

cmpt:
  component_ablation:
    enabled: true
